language: python
matrix:
  include:
    # 3.3 used to work as well but somehow failed Feb 2017 for no apparent
    # reason saying that package "python" cannot be built
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran"

# command to install dependencies
# nose already installed
install:
  - pip install matplotlib --upgrade
  - pip install easydev
  - pip install pytest pytest-xdist pytest-cov coveralls
# # command to run tests, e.g. python setup.py test
script:
  - pytest -v --durations=10  test/ --cov=spectrum --cov-report term --timeout 300 

after_success:
  coveralls
